const JWT_ALG = "HS256";

const JWT_REFRESH_TOKEN_GRACE_PERIOD_SECONDS = 10;

const JWT_ACCESS_TOKEN_NAME =
	process.env.NEXT_PUBLIC_ACCESS_TOKEN_NAME || "auth_token";

const JWT_ACCESS_TOKEN_SECRET =
	process.env.ACCESS_TOKEN_SECRET || "dev_access_secret";

const JWT_ACCESS_TOKEN_TIME_IN_SECONDS = 60 * 60; // 1h

const JWT_REFRESH_TOKEN_NAME =
	process.env.NEXT_PUBLIC_REFRESH_TOKEN_NAME || "refresh_token";

const JWT_REFRESH_TOKEN_SECRET =
	process.env.REFRESH_TOKEN_SECRET || "dev_refresh_secret";

const JWT_REFRESH_TOKEN_TIME_IN_SECONDS = 60 * 60 * 24 * 7; // 7d

export {
	JWT_ACCESS_TOKEN_NAME,
	JWT_ACCESS_TOKEN_SECRET,
	JWT_ACCESS_TOKEN_TIME_IN_SECONDS,
	JWT_ALG,
	JWT_REFRESH_TOKEN_GRACE_PERIOD_SECONDS,
	JWT_REFRESH_TOKEN_NAME,
	JWT_REFRESH_TOKEN_SECRET,
	JWT_REFRESH_TOKEN_TIME_IN_SECONDS,
};
